baseURL = "https://jacquessmuts.github.io/"
languageCode = "en-us"
title = "Jacques Smuts Blog"
theme = "hugo-nuo"

[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Works"
  weight = 20
  identifier = "works"
  url = "https://github.com/jacquessmuts"

[params]
  email = "githubpage@jacquessmuts.com"
  github = "jacquessmuts"
  twitter = "jacquessmuts"