baseURL = "https://jacquessmuts.github.io/"
languageCode = "en-us"
title = "Jacques Smuts"
theme = "hugo-stack"
enableRobotsTXT = true
googleAnalytics = "UA-139178159-1"
disqusShortname = "jacquessmuts"

pygmentsUseClasses=true
pygmentsCodeFences=true
canonifyurls = true

copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License，please give source if you wish to quote or reproduce."


